[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['cd backend && npx prisma generate && npm run build']

[start]
cmd = 'cd backend && npx prisma migrate deploy && node dist/main'